import json

import requests

# nutri calc database nutrient list
ncdb_nutrient_list = [
    {"id": 0, "name_list": ["calories", "Energy"]},
    {
        "id": 1,
        "name_list": [
            "carbohydrates",
            "Carbohydrate, by difference",
            "Carbohydrate, by summation",
        ],
    },
    {"id": 2, "name_list": ["fiber", "Fiber, total dietary", "Total dietary fiber"]},
    {"id": 3, "name_list": ["proteins", "Protein"]},
    {"id": 4, "name_list": ["cholestrol", "Cholesterol"]},
    {"id": 5, "name_list": ["total_fats", "Total lipid (fat)", "Total fat (NLEA)"]},
    {
        "id": 6,
        "name_list": ["monounsaturated_fats", "Fatty acids, total monounsaturated"],
    },
    {
        "id": 7,
        "name_list": ["polyunsaturated_fats", "Fatty acids, total polyunsaturated"],
    },
    {"id": 8, "name_list": ["saturated_fats", "Fatty acids, total saturated"]},
    {"id": 9, "name_list": ["trans_fats","Fatty acids, total trans"]},
    {"id": 10, "name_list": ["omega_3"]},
    {"id": 11, "name_list": ["vitamin_A", "Vitamin A, RAE"]},
    {"id": 12, "name_list": ["vitamin_B1", "Thiamin"]},
    {"id": 13, "name_list": ["vitamin_B2", "Riboflavin"]},
    {"id": 14, "name_list": ["vitamin_B3", "Niacin"]},
    {"id": 15, "name_list": ["vitamin_B5", "Pantothenic acid"]},
    {"id": 16, "name_list": ["vitamin_B6", "Vitamin B-6"]},
    {"id": 17, "name_list": ["vitamin_B12", "Vitamin B-12"]},
    {"id": 18, "name_list": ["vitamin_C", "Vitamin C, total ascorbic acid"]},
    {"id": 19, "name_list": ["vitamin_D", "Vitamin D (D2 + D3), International Units"]},
    {"id": 20, "name_list": ["vitamin_E", "Vitamin E (alpha-tocopherol)", "Vitamin E"]},
    {"id": 21, "name_list": ["vitamin_k", "Vitamin K (phylloquinone)"]},
    {"id": 22, "name_list": ["choline", "Choline, total"]},
    {"id": 23, "name_list": ["folate", "Folate, total"]},
    {"id": 24, "name_list": ["calcium", "Calcium, Ca"]},
    {"id": 25, "name_list": ["chloride", "Chlorine, Cl"]},
    {"id": 26, "name_list": ["chromium","Chromium, Cr"]},
    {"id": 27, "name_list": ["copper", "Copper, Cu"]},
    {"id": 28, "name_list": ["fluoride", "Fluoride, F"]},
    {"id": 29, "name_list": ["iodine", "Iodine, I"]},
    {"id": 30, "name_list": ["iron", "Iron, Fe"]},
    {"id": 31, "name_list": ["magnesium", "Magnesium, Mg"]},
    {"id": 32, "name_list": ["manganese", "Manganese, Mn"]},
    {"id": 33, "name_list": ["phosphorus", "Phosphorus, P"]},
    {"id": 34, "name_list": ["potatssium", "Potassium, K"]},
    {"id": 35, "name_list": ["selenium", "Selenium, Se"]},
    {"id": 36, "name_list": ["sodium", "Sodium, Na"]},
    {"id": 37, "name_list": ["sulfur", "Sulfur, S"]},
    {"id": 38, "name_list": ["zinc", "Zinc, Zn"]},
    {"id": 39, "name_list": ["creatine"]},
    {"id": 40, "name_list": ["caffeine", "Caffeine"]},
    {"id": 41, "name_list": ["good_bacteria"]},
    {"id": 42, "name_list": ["mercury"]},
    {"id": 43, "name_list": ["nitrates_and_nitrites"]},
    {"id": 44, "name_list": ["artificial_food_colors"]},
    {"id": 45, "name_list": ["vitamin_B7","biotin"]},
    {"id": 46, "name_list": ["molybdenum", "Molybdenum, Mo"]},
    {"id": 47, "name_list": ["linoleic_acid"]},
    {"id": 48, "name_list": ["a-linolenic_acid"]},
    {"id": 49, "name_list": ["nickel", "Nickel, Ni"]},
    {"id": 50, "name_list": ["boron", "Boron, B"]},
    {"id": 51, "name_list": ["arsenic"]},
    {"id": 52, "name_list": ["chromium"]},
    {"id": 53, "name_list": ["silicon"]},
    {"id": 54, "name_list": ["sulfate"]},
    {"id": 55, "name_list": ["vanadium"]},
    {"id": 56, "name_list": ["total_sugar", "Sugars, total including NLEA", "Sugars, Total"]},
    {"id": 57, "name_list": ["glucose"]},
    {"id": 58, "name_list": ["fructose"]},
    {"id": 59, "name_list": ["sucrose"]},
    {"id": 60, "name_list": ["alcohol", "Alcohol, ethyl"]},
]

# usda_components = [
#     "Water",
#     "Energy (Atwater General Factors)",
#     "Energy (Atwater Specific Factors)",
#     "Energy",
#     "Energy",
#     "Nitrogen",
#     "Protein",
#     "Total lipid (fat)",
#     "Total fat (NLEA)",
#     "Ash",
#     "Carbohydrate, by difference",
#     "Carbohydrate, by summation",
#     "Fiber, total dietary",
#     "Fiber, soluble",
#     "Fiber, insoluble",
#     "Total dietary fiber (AOAC 2011.25)",
#     "High Molecular Weight Dietary Fiber (HMWDF)",
#     "Low Molecular Weight Dietary Fiber (LMWDF)",
#     "Beta-glucan",
#     "Sugars, Total",
#     "Sugars, total including NLEA",
#     "Sugars, added",
#     "Sucrose",
#     "Glucose",
#     "Fructose",
#     "Lactose",
#     "Maltose",
#     "Galactose",
#     "Starch",
#     "Raffinose",
#     "Stachyose",
#     "Verbascose",
#     "Sorbitol",
#     "Xylitol",
#     "Inositol",
#     "Acetic acid",
#     "Citric acid",
#     "Lactic acid",
#     "Malic acid",
#     "Oxalic acid",
#     "Pyruvic acid",
#     "Quinic acid",
#     "Calcium, Ca",
#     "Iron, Fe",
#     "Magnesium, Mg",
#     "Phosphorus, P",
#     "Potassium, K",
#     "Sodium, Na",
#     "Zinc, Zn",
#     "Copper, Cu",
#     "Manganese, Mn",
#     "Iodine, I",
#     "Selenium, Se",
#     "Fluoride, F",
#     "Sulfur, S",
#     "Nickel, Ni",
#     "Molybdenum, Mo",
#     "Cobalt, Co",
#     "Boron, B",
#     "Vitamin C, total ascorbic acid",
#     "Thiamin",
#     "Riboflavin",
#     "Niacin",
#     "Pantothenic acid",
#     "Vitamin B-6",
#     "Biotin",
#     "Folate, total",
#     "Folic acid",
#     "Folate, food",
#     "Folate, DFE",
#     "Choline, total",
#     "Choline, free",
#     "Choline, from phosphocholine",
#     "Choline, from phosphotidyl choline",
#     "Choline, from glycerophosphocholine",
#     "Choline, from sphingomyelin",
#     "Betaine",
#     "Vitamin B-12",
#     "Vitamin B-12, added",
#     "Vitamin A, RAE",
#     "Retinol",
#     "Carotene, beta",
#     "cis-beta-Carotene",
#     "trans-beta-Carotene",
#     "Carotene, alpha",
#     "Carotene, gamma",
#     "Cryptoxanthin, beta",
#     "Cryptoxanthin, alpha",
#     "Vitamin A, IU",
#     "Lycopene",
#     "cis-Lycopene",
#     "trans-Lycopene",
#     "Lutein + zeaxanthin",
#     "cis-Lutein/Zeaxanthin",
#     "Lutein",
#     "Zeaxanthin",
#     "Phytoene",
#     "Phytofluene",
#     "Vitamin E",
#     "Vitamin E (alpha-tocopherol)",
#     "Vitamin E, added",
#     "Tocopherol, beta",
#     "Tocopherol, gamma",
#     "Tocopherol, delta",
#     "Tocotrienol, alpha",
#     "Tocotrienol, beta",
#     "Tocotrienol, gamma",
#     "Tocotrienol, delta",
#     "Vitamin D (D2 + D3), International Units",
#     "Vitamin D (D2 + D3)",
#     "Vitamin D2 (ergocalciferol)",
#     "Vitamin D3 (cholecalciferol)",
#     "25-hydroxycholecalciferol",
#     "Vitamin D4",
#     "Vitamin K (phylloquinone)",
#     "Vitamin K (Dihydrophylloquinone)",
#     "Vitamin K (Menaquinone-4)",
#     "Fatty acids, total saturated",
#     "SFA 4:0",
#     "SFA 5:0",
#     "SFA 6:0",
#     "SFA 7:0",
#     "SFA 8:0",
#     "SFA 9:0",
#     "SFA 10:0",
#     "SFA 11:0",
#     "SFA 12:0",
#     "SFA 13:0",
#     "SFA 14:0",
#     "SFA 15:0",
#     "SFA 16:0",
#     "SFA 17:0",
#     "SFA 18:0",
#     "SFA 20:0",
#     "SFA 21:0",
#     "SFA 22:0",
#     "SFA 23:0",
#     "SFA 24:0",
#     "Fatty acids, total monounsaturated",
#     "MUFA 12:1",
#     "MUFA 14:1",
#     "MUFA 14:1 c",
#     "MUFA 15:1",
#     "MUFA 16:1",
#     "MUFA 16:1 c",
#     "MUFA 17:1",
#     "MUFA 17:1 c",
#     "MUFA 18:1",
#     "MUFA 18:1 c",
#     "MUFA 18:1-11 t (18:1t n-7)",
#     "MUFA 20:1",
#     "MUFA 20:1 c",
#     "MUFA 22:1",
#     "MUFA 22:1 c",
#     "MUFA 22:1 n-9",
#     "MUFA 22:1 n-11",
#     "MUFA 24:1 c",
#     "Fatty acids, total polyunsaturated",
#     "PUFA 18:2",
#     "PUFA 18:2 c",
#     "PUFA 18:2 n-6 c,c",
#     "PUFA 18:2 CLAs",
#     "PUFA 18:2 i",
#     "PUFA 18:3",
#     "PUFA 18:3 c",
#     "PUFA 18:3 n-3 c,c,c (ALA)",
#     "PUFA 18:3 n-6 c,c,c",
#     "PUFA 18:3i",
#     "PUFA 18:4",
#     "PUFA 20:2 c",
#     "PUFA 20:2 n-6 c,c",
#     "PUFA 20:3",
#     "PUFA 20:3 c",
#     "PUFA 20:3 n-3",
#     "PUFA 20:4 n-6",
#     "PUFA 20:3 n-9",
#     "PUFA 22:3",
#     "PUFA 20:4",
#     "PUFA 20:4c",
#     "PUFA 2:4 n-6",
#     "PUFA 20:5c",
#     "PUFA 20:5 n-3 (EPA)",
#     "PUFA 22:2",
#     "PUFA 21:5",
#     "PUFA 22:5 c",
#     "PUFA 22:4",
#     "PUFA 22:5 n-3 (DPA)",
#     "PUFA 22:6 c",
#     "PUFA 22:6 n-3 (DHA)",
#     "Fatty acids, total trans",
#     "Fatty acids, total trans-monoenoic",
#     "TFA 14:1 t",
#     "TFA 16:1 t",
#     "TFA 18:1 t",
#     "TFA 20:1 t",
#     "TFA 22:1 t",
#     "Fatty acids, total trans-dienoic",
#     "TFA 18:2 t not further defined",
#     "TFA 18:2 t",
#     "TFA 18:2 t,t",
#     "Fatty acids, total trans-polyenoic",
#     "TFA 18:3 t",
#     "Cholesterol",
#     "Phytosterols",
#     "Stigmastadiene",
#     "Stigmasterol",
#     "Campesterol",
#     "Brassicasterol",
#     "Beta-sitosterol",
#     "Ergosta-7-enol",
#     "Ergosta-7,22-dienol",
#     "Ergosta-5,7-dienol",
#     "Ergosterol",
#     "Campestanol",
#     "Beta-sitostanol",
#     "Delta-5-avenasterol",
#     "Delta-7-Stigmastenol",
#     "Phytosterols, other",
#     "Ergothioneine",
#     "Tryptophan",
#     "Threonine",
#     "Isoleucine",
#     "Leucine",
#     "Lysine",
#     "Methionine",
#     "Cystine",
#     "Phenylalanine",
#     "Tyrosine",
#     "Valine",
#     "Arginine",
#     "Histidine",
#     "Alanine",
#     "Aspartic acid",
#     "Glutamic acid",
#     "Glycine",
#     "Proline",
#     "Serine",
#     "Hydroxyproline",
#     "Cysteine",
#     "Alcohol, ethyl",
#     "Caffeine",
#     "Theobromine",
#     "Daidzein",
#     "Genistein",
#     "Daidzin",
#     "Genistin",
#     "Glycitin",
#     "Epigallocatechin-3-gallate",
#     "Specific Gravity",
#     "Ribose",
#     "Total sugar alcohols",
#     "Chlorine, Cl",
#     "Chromium, Cr",
#     "Vitamin E (label entry primarily)",
#     "5-methyl tetrahydrofolate (5-MTHF)",
#     "10-Formyl folic acid (10HCOFA)",
#     "5-Formyltetrahydrofolic acid",
#     "Phenolic acids, total",
#     "Glutamine",
#     "Taurine",
#     "Inulin",
#     "Carbohydrate, other",
# ]

ncdb_nutrient_name_list = []

for ncdb_nutrient in ncdb_nutrient_list:
    ncdb_nutrient_name_list.extend(ncdb_nutrient["name_list"])

# count = 0
# for usda_component in usda_components:
#     includes_ignorecase = usda_component.lower() in [ncdb_nutrient.lower() for ncdb_nutrient in ncdb_nutrient_name_list]
#     has_colon = ":" in usda_component
#     if not (includes_ignorecase or has_colon):
#         print(usda_component)
#         count += 1
        


# fdc_id_list = [
#     # peanuts, dry roasted, salted
#     2342994,
#     # Egg, whole, boiled or poached
#     2342629,
#     # Spices, turmeric, ground172231
#     172231,
# ]

# json_text = requests.get(
#     f"https://api.nal.usda.gov/fdc/v1/food/2342994?api_key=<lololololololol>"
# ).text
# _dict = json.loads(json_text)

# print(_dict["inputFoods"][0]["amount"])
# print(_dict["inputFoods"][0]["unit"])
# print(_dict["description"])
# for nutrient in _dict["foodNutrients"]:
#     print("-------------------------------------------")
#     print(nutrient["nutrient"]["name"])
#     print(nutrient["amount"])
#     print(nutrient["nutrient"]["unitName"])

# rmemeber to make sure the nutrient matching is not case sensitive

# remember for some reason the USDA does not record omega 3
